### ISSUE TITLE
Any hope for a LICENSE file for this?

### ISSUE THREAD

**Issue by JeetKunDoug** [Stapelzeiger/cmp_mem_access#1]
Would love to be able to use some of this, but I have no idea what you would intend the license to be. Given cmp is MIT, any thought to using the MIT license here as well?

https://github.com/camgunz/cmp/blob/master/LICENSE

Thanks

**Comment by Stapelzeiger** [comment]
Sure, I put it under MIT license.

**Comment by JeetKunDoug** [comment]
Thank you kindly - appreciate it.
